

// const ADD_TODO ="ADD_TODO"

const ADD_TODO_LOADING = "ADD_TODO_LOADING"

const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"

const ADD_TODO_ERROR  ="ADD_TODO_ERROR"


const GET_TODO_LOADING = "GET_TODO_LOADING"

const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"

const GET_TODO_ERROR  =  "GET_TODO_ERROR"

export {ADD_TODO_LOADING,ADD_TODO_SUCCESS,ADD_TODO_ERROR, GET_TODO_LOADING , GET_TODO_SUCCESS , GET_TODO_ERROR}